### ISSUE TITLE
Not working for planned series

### ISSUE THREAD

**Issue by Hoaas** [Znuff/limnoria-tvmaze#2]
Error: TypeError: 'NoneType' object is not subscriptable

Occurs on shows with no episodes yet, like http://www.tvmaze.com/shows/2781/twin-peaks

(I have converted to python3 with the 2to3 tool)

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/supybot/callbacks.py", line 1274, in _callCommand
    pass
  File "/usr/lib/python3.4/site-packages/supybot/utils/python.py", line 91, in g
    finally:
  File "/usr/lib/python3.4/site-packages/supybot/callbacks.py", line 1255, in callCommand
    msg.args[0], msg.prefix)
  File "/usr/lib/python3.4/site-packages/supybot/commands.py", line 1080, in newf
    f(self, irc, msg, args, _state.args, *_state.kwargs)
  File "/home/.../.supybot/plugins/tvmaze/plugin.py", line 57, in tv
    show['premiered'][:4], show['status'])
TypeError: 'NoneType' object is not subscriptable
ERROR 2015-09-29T09:30:44 supybot Exception id: 0xb2045

**Comment by Hoaas** [comment]
Sweet. :D
